[features]
seeds = false
skip-lint = false

[programs.devnet]
server_registry = "B6xe3XtwyokW7Nsud63otwagnJS4GMkAutWXwftMtCKh"

[programs.localnet]
server_registry = "B6xe3XtwyokW7Nsud63otwagnJS4GMkAutWXwftMtCKh"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/francklin99/.config/solana/id.json"

[scripts]
test = "node --test dist/test/*.test.js"

[workspace]
members = ["programs/server-registry"]
