import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { forgeHome } from "./persistence.js";

/**
 * The urlmcp browser-connector Chrome extension, embedded as source strings so it ships inside the single bundled
 * binary (no extra files in the npm tarball) and is written to disk on `urlmcp install-extension`. The extension
 * runs inside the user's REAL, already-signed-in Chrome and drives a tab via chrome.debugger (CDP) to capture a
 * page in their authenticated session, returning DOM + XHR/fetch traffic to the local bridge (extension-bridge.ts).
 *
 * Canonical source lives here; `install-extension` materializes it (baking in the bridge port) into a directory the
 * user loads unpacked at chrome://extensions. Keep EXTENSION_VERSION in step with the server version.
 */

export const EXTENSION_VERSION = "0.5.0";
const DEFAULT_PORT = Number(process.env["FORGE_EXT_PORT"]) || 47_900;

const MANIFEST = (version: string): string =>
  JSON.stringify(
    {
      manifest_version: 3,
      name: "urlmcp connector",
      version,
      description: "Lets urlmcp capture pages using your real, already-signed-in browser session (LinkedIn, Gmail, X, etc.).",
      permissions: ["debugger", "tabs", "alarms"],
      host_permissions: ["<all_urls>", "http://127.0.0.1/*", "http://localhost/*"],
      background: { service_worker: "background.js" },
    },
    null,
    2,
  );

// NOTE: this string is the extension's runtime JS. It deliberately uses NO `${...}` template literals (so it can be
// stored as a plain TS template) — the bridge port is the single `__PORT__` placeholder, substituted at install.
const BACKGROUND = String.raw`// urlmcp connector — drives the user's real, signed-in browser to capture a page for urlmcp.
// Generated by "urlmcp install-extension". Talks only to the local urlmcp bridge on 127.0.0.1.
const PORT = __PORT__;
const BASE = "http://127.0.0.1:" + PORT + "/urlmcp";
let running = false;
let backoff = 1500;

const sleep = (ms) => new Promise((r) => setTimeout(r, ms));

function dbgSend(target, method, params) {
  return new Promise((resolve, reject) => {
    chrome.debugger.sendCommand(target, method, params || {}, (result) => {
      const err = chrome.runtime.lastError;
      if (err) reject(new Error(err.message)); else resolve(result || {});
    });
  });
}
function dbgAttach(target, version) {
  return new Promise((resolve, reject) => {
    chrome.debugger.attach(target, version, () => {
      const err = chrome.runtime.lastError;
      if (err) reject(new Error(err.message)); else resolve();
    });
  });
}
function dbgDetach(target) {
  return new Promise((resolve) => {
    chrome.debugger.detach(target, () => { void chrome.runtime.lastError; resolve(); });
  });
}
function tabsCreate(props) {
  return new Promise((resolve, reject) => {
    chrome.tabs.create(props, (tab) => {
      const err = chrome.runtime.lastError;
      if (err) reject(new Error(err.message)); else resolve(tab);
    });
  });
}
function tabsRemove(id) {
  return new Promise((resolve) => { chrome.tabs.remove(id, () => { void chrome.runtime.lastError; resolve(); }); });
}

function ctOf(headers) {
  if (!headers) return "";
  for (const k of Object.keys(headers)) if (k.toLowerCase() === "content-type") return String(headers[k] || "");
  return "";
}

async function evalIn(target, expression) {
  try {
    const r = await dbgSend(target, "Runtime.evaluate", { expression: expression, returnByValue: true });
    return r && r.result ? r.result.value : undefined;
  } catch (e) { return undefined; }
}

function b64ToUtf8(b64) {
  try {
    const bin = atob(b64);
    const bytes = new Uint8Array(bin.length);
    for (let i = 0; i < bin.length; i++) bytes[i] = bin.charCodeAt(i);
    return new TextDecoder("utf-8").decode(bytes);
  } catch (e) { return ""; }
}

async function waitForLoad(target, timeoutMs) {
  const deadline = Date.now() + timeoutMs;
  // First wait for the navigation to actually leave about:blank (so we don't read the blank tab's readyState).
  while (Date.now() < deadline) {
    const href = await evalIn(target, "location.href");
    if (href && href !== "about:blank") break;
    await sleep(150);
  }
  while (Date.now() < deadline) {
    const state = await evalIn(target, "document.readyState");
    if (state === "complete") return;
    await sleep(250);
  }
}

// True if the page looks like a sign-in / CAPTCHA wall a human must clear. Mirrors the Node-side isHumanWall: a
// password field on a login-ish/thin page, or a CAPTCHA marker on a THIN page (so real content doesn't trigger).
function wallCheckExpr() {
  return "(function(){try{" +
    "var t=(document.title||'');" +
    "var body=document.body?document.body.innerText:'';" +
    "var txt=body.replace(/\\s+/g,' ').trim();" +
    "var thin=txt.length<3000;" +
    "var pw=!!document.querySelector('input[type=password]');" +
    "var bot=/captcha|verify you are human|are you a human|just a moment|checking your browser|unusual traffic|access denied|attention required/i.test((t+' '+txt.slice(0,4000)));" +
    "var loginish=/sign[ -]?in|log[ -]?in|signin|login|authwall/i.test(t)||/\\/(login|signin|sign-in|authwall|checkpoint|uas\\/login)/i.test(location.href);" +
    "return (pw&&(loginish||thin))||(bot&&thin);" +
    "}catch(e){return false;}})()";
}
async function isWalled(target) { return (await evalIn(target, wallCheckExpr())) === true; }

// A fixed banner telling the user to finish signing in, right in the tab they're looking at. PRIVACY: the extension
// only ever checks WHETHER the wall is gone — it never reads the password / values the user types.
function bannerExpr(show) {
  if (show) {
    return "(function(){try{var d=document;if(d.getElementById('__urlmcp_banner__'))return;var b=d.createElement('div');b.id='__urlmcp_banner__';" +
      "b.textContent='urlmcp — please sign in / solve the CAPTCHA. Capture continues automatically once you are through. Your password is never captured.';" +
      "b.setAttribute('style','position:fixed;top:0;left:0;right:0;z-index:2147483647;background:#0b5;color:#fff;font:600 14px/1.6 system-ui,Arial,sans-serif;padding:10px 16px;text-align:center');" +
      "d.documentElement.appendChild(b);}catch(e){}})()";
  }
  return "(function(){try{var e=document.getElementById('__urlmcp_banner__');if(e)e.remove();}catch(e){}})()";
}

async function runCapture(cmd) {
  const tab = await tabsCreate({ url: "about:blank", active: true });
  const target = { tabId: tab.id };
  const reqs = new Map();
  const listener = (src, method, params) => {
    if (!src || src.tabId !== tab.id) return;
    if (method === "Network.requestWillBeSent") {
      const r = params.request || {};
      reqs.set(params.requestId, { url: r.url, method: r.method, requestHeaders: r.headers || {}, reqContentType: ctOf(r.headers), requestPostData: r.postData, type: params.type });
    } else if (method === "Network.responseReceived") {
      const cur = reqs.get(params.requestId) || {};
      const resp = params.response || {};
      cur.status = resp.status;
      cur.contentType = ctOf(resp.headers) || resp.mimeType || "";
      cur.type = params.type || cur.type;
      reqs.set(params.requestId, cur);
    }
  };
  chrome.debugger.onEvent.addListener(listener);
  try {
    await dbgAttach(target, "1.3");
    await dbgSend(target, "Network.enable", {});
    await dbgSend(target, "Page.enable", {});
    await dbgSend(target, "Page.navigate", { url: cmd.url });
    await waitForLoad(target, cmd.navTimeoutMs || 30000);
    await sleep(cmd.settleMs || 2500);

    // Sign-in / CAPTCHA handoff: if the page is a wall, show a banner and WAIT for the user to clear it in this
    // (their own, already-focused) tab, then continue capturing the authenticated page in the same session.
    if (cmd.authHandoff && (await isWalled(target))) {
      const deadline = Date.now() + (cmd.authTimeoutMs || 300000);
      await evalIn(target, bannerExpr(true));
      while (Date.now() < deadline && (await isWalled(target))) await sleep(2000);
      await evalIn(target, bannerExpr(false));
      await sleep(cmd.settleMs || 2500); // let the now-authenticated page settle so its XHR is captured
    }

    const network = [];
    for (const entry of reqs) {
      const rid = entry[0];
      const info = entry[1];
      if (info.type !== "XHR" && info.type !== "Fetch") continue;
      if (!/^https?:\/\//i.test(info.url || "")) continue;
      let responseBody;
      if (/json/i.test(info.contentType || "")) {
        try {
          const r = await dbgSend(target, "Network.getResponseBody", { requestId: rid });
          responseBody = r.base64Encoded ? b64ToUtf8(r.body) : r.body;
        } catch (e) { /* body gone */ }
      }
      network.push({ method: info.method, url: info.url, requestHeaders: info.requestHeaders, reqContentType: info.reqContentType, requestPostData: info.requestPostData, status: info.status, contentType: info.contentType, responseBody: responseBody });
    }
    const html = (await evalIn(target, "document.documentElement.outerHTML")) || "";
    const title = (await evalIn(target, "document.title")) || "";
    const finalUrl = (await evalIn(target, "location.href")) || cmd.url;
    return { url: finalUrl, title: title, html: html, network: network };
  } finally {
    chrome.debugger.onEvent.removeListener(listener);
    await dbgDetach(target);
    if (tab && tab.id != null) await tabsRemove(tab.id);
  }
}

async function postResult(payload) {
  try {
    await fetch(BASE + "/result", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) });
  } catch (e) { /* bridge gone; drop */ }
}

async function loop() {
  if (running) return;
  running = true;
  try { await fetch(BASE + "/hello"); } catch (e) { /* bridge not up yet */ }
  while (true) {
    let cmd = null;
    try {
      const res = await fetch(BASE + "/next");
      cmd = await res.json();
      backoff = 1500;
    } catch (e) {
      await sleep(backoff);
      backoff = Math.min(backoff * 2, 10000);
      continue;
    }
    if (!cmd || cmd.none) continue;
    if (cmd.type === "capture") {
      try {
        const result = await runCapture(cmd);
        await postResult(Object.assign({ id: cmd.id, ok: true }, result));
      } catch (e) {
        await postResult({ id: cmd.id, ok: false, error: String((e && e.message) || e) });
      }
    }
  }
}

chrome.runtime.onInstalled.addListener(() => loop());
chrome.runtime.onStartup.addListener(() => loop());
try {
  chrome.alarms.create("urlmcp-keepalive", { periodInMinutes: 0.5 });
  chrome.alarms.onAlarm.addListener(() => loop());
} catch (e) { /* alarms unavailable */ }
loop();
`;

const READMETXT = (port: number): string =>
  [
    "urlmcp connector (Chrome extension)",
    "===================================",
    "",
    "This extension lets urlmcp capture pages using YOUR real, already-signed-in browser",
    "session, so logged-in sites (LinkedIn, Gmail, X, ...) work without a separate browser.",
    "",
    "Load it (one-time):",
    "  1. Open chrome://extensions",
    "  2. Turn on 'Developer mode' (top-right)",
    "  3. Click 'Load unpacked' and select this folder",
    "  4. Keep Chrome open.",
    "",
    "Then run urlmcp with the extension backend:",
    "  FORGE_BROWSER_BACKEND=extension",
    "",
    "It talks ONLY to the local urlmcp bridge on http://127.0.0.1:" + port + " — nothing leaves your machine.",
    "Chrome will show 'urlmcp connector started debugging this browser' while a capture runs; that is expected.",
  ].join("\n");

export interface ExtensionFile {
  path: string;
  content: string;
}

/** The materialized extension files (manifest + worker + readme), with the bridge port baked into the worker. */
export function extensionFiles(port: number = DEFAULT_PORT, version: string = EXTENSION_VERSION): ExtensionFile[] {
  return [
    { path: "manifest.json", content: MANIFEST(version) },
    { path: "background.js", content: BACKGROUND.replace("__PORT__", String(port)) },
    { path: "README.txt", content: READMETXT(port) },
  ];
}

/** Write the extension to disk (default ~/.urlmcp/extension) and return where it landed. */
export function installExtension(destDir?: string, port: number = DEFAULT_PORT): { dir: string; files: string[] } {
  const dir = destDir || join(forgeHome(), "extension");
  mkdirSync(dir, { recursive: true });
  const files = extensionFiles(port);
  for (const f of files) writeFileSync(join(dir, f.path), f.content);
  return { dir, files: files.map((f) => f.path) };
}
